Controllers/RenderLayoutController.cs
using System.Linq;
using System.Web.Mvc;
using BTL_Mvc.Respository.ImpRespository;

namespace BTL_Mvc.Controllers
{
    public class RenderLayoutController : Controller
    {
        // GET: RenderLayout
        public ActionResult LoadHeader()
        {
            CategoriesRepository categories = new CategoriesRepository();
            return PartialView("~/Views/Shared/_Header.cshtml", categories.findAll().Take(5));
        }
    }
}

Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Login V4</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--===============================================================================================-->
    <link rel="icon" type="image/png" href="~/Content/img/bg-01.jpg" />
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Content/vendor/bootstrap/css/bootstrap.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Content/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Content/fonts/iconic/css/material-design-iconic-font.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Content/vendor/animate/animate.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Content/vendor/css-hamburgers/hamburgers.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Content/vendor/animsition/css/animsition.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Content/vendor/select2/select2.min.css">

    <link rel="stylesheet" type="text/css" href="~/Content/vendor/daterangepicker/daterangepicker.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Content/css/util.css">
    <link rel="stylesheet" type="text/css" href="~/Content/css/mainAuth.css">
    <!--===============================================================================================-->
</head>
<body>

    <div class="limiter">
        <div class="container-login100" style="background-image: url('../../Content/img/bg-01.jpg');">
            <div class="wrap-login100 p-l-55 p-r-55 p-t-65 p-b-54">
                @RenderBody()
            </div>
        </div>
    </div>


    <div id="dropDownSelect1"></div>

    <!--===============================================================================================-->
    <script src="~/Content/vendor/jquery/jquery-3.2.1.min.js"></script>
    <!--===============================================================================================-->
    <script src="~/Content/vendor/animsition/js/animsition.min.js"></script>
    <!--===============================================================================================-->
    <script src="~/Content/vendor/bootstrap/js/popper.js></script>
    <script src="~/Content/bootstrap/js/bootstrap.min.js"></script>
    <!--===============================================================================================-->
    <script src="~/Content/select2/select2.min.js"></script>
    <!--===============================================================================================-->
    <script src="~/Content/vendor/daterangepicker/moment.min.js"></script>
    <script src="~/Content/vendor/daterangepicker/daterangepicker.js"></script>
    <!--===============================================================================================-->
    <script src="~/Content/vendor/countdowntime/countdowntime.js"></script>
    <!--===============================================================================================-->
    <script src="~/Scripts/js/authMain.js"></script>

</body>
</html>

Views/Shared/_AuthLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>_AuthLayout</title>
</head>
<body>
    <div>
        @RenderBody();
    </div>
</body>
</html>

Views/Shared/_Footer.cshtml
<!-- top footer -->
<div class="section">
    <!-- container -->
    <div class="container">
        <!-- row -->
        <div class="row">
            <div class="col-md-3 col-xs-6">
                <div class="footer">
                    <h3 class="footer-title">Giới thiệu</h3>
                    <p>Cửa hàng chúng tôi đã có 5 năm kinh nghiệm về kinh doanh mỹ phẩm, phụ kiện dành cho nữ</p>
                    <ul class="footer-links">
                        <li><a href="#"><i class="fa fa-map-marker"></i>số 3 cầu giấy</a></li>
                        <li><a href="#"><i class="fa fa-phone"></i>024 3766 3311</a></li>
                        <li><a href="#"><i class="fa fa-envelope-o"></i>daihocGTVT@gmail.com</a></li>
                    </ul>
                </div>
            </div>

            <div class="col-md-3 col-xs-6">
                <div class="footer">
                    <h3 class="footer-title">Danh mục</h3>
                    <ul class="footer-links">
                        <li><a href="#">Bán chạy</a></li>
                        <li><a href="#">Nước hoa</a></li>
                        <li><a href="#">Son</a></li>
                        <li><a href="#">Quần áo</a></li>
                        <li><a href="#">Giày dép</a></li>
                    </ul>
                </div>
            </div>

            <div class="clearfix visible-xs"></div>

            <div class="col-md-3 col-xs-6">
                <div class="footer">
                    <h3 class="footer-title">Thông tin</h3>
                    <ul class="footer-links">
                        <li><a href="#">Giới thiệu</a></li>
                        <li><a href="#">Liên hệ</a></li>
                        <li><a href="#">Các Chính sách</a></li>
                        <li><a href="#">Mua Hàng</a></li>
                        <li><a href="#">Các điều khoản và hỗ trợ</a></li>
                    </ul>
                </div>
            </div>

            <div class="col-md-3 col-xs-6">
                <div class="footer">
                    <h3 class="footer-title">Dịch vụ</h3>
                    <ul class="footer-links">
                        <li><a href="#">Tài khoản</a></li>
                        <li><a href="#">Xem giỏ hàng</a></li>
                        <li><a href="#">Mục yêu thích</a></li>
                        <li><a href="#">Theo dõi đơn hàng</a></li>
                        <li><a href="#">Hỗ trợ</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <!-- /row -->
    </div>
    <!-- /container -->
</div>
<!-- /top footer -->
<!-- bottom footer -->
<div id="bottom-footer" class="section">
    <div class="container">
        <!-- row -->
        <div class="row">
            <div class="col-md-12 text-center">
                <ul class="footer-payments">
                    <li><a href="#"><i class="fa fa-cc-visa"></i></a></li>
                    <li><a href="#"><i class="fa fa-credit-card"></i></a></li>
                    <li><a href="#"><i class="fa fa-cc-paypal"></i></a></li>
                    <li><a href="#"><i class="fa fa-cc-mastercard"></i></a></li>
                    <li><a href="#"><i class="fa fa-cc-discover"></i></a></li>
                    <li><a href="#"><i class="fa fa-cc-amex"></i></a></li>
                </ul>
                <span class="copyright">
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    Năm &copy;
                    <script>document.write(new Date().getFullYear());</script> Cửa hàng mỹ phầm ABCXYZ <i class="fa fa-heart-o" aria-hidden="true"></i> của <a href="https://colorlib.com" target="_blank">HLLNNN</a>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                </span>
            </div>
        </div>
        <!-- /row -->
    </div>
    <!-- /container -->
</div>
<!-- /bottom footer -->

Views/Shared/_Header.cshtml
@model IEnumerable<BTL_Mvc.Models.Entities.Loai>
    <!-- TOP HEADER -->
    <div id="top-header">
        <div class="container">
            <ul class="header-links pull-left">
                <li><a href="#"><i class="fa fa-phone"></i> 024 3766 3311</a></li>
                <li><a href="#"><i class="fa fa-envelope-o"></i> daihocGTVT@gmail.com</a></li>
                <li><a href="#"><i class="fa fa-map-marker"></i> số 3 cầu giấy </a></li>
            </ul>
            <ul class="header-links pull-right">
                <li><a href="#"><i class="fa fa-dollar"></i> Tiền</a></li>
                <li><a href="#"><i class="fa fa-user-o"></i> Tài Khoản</a></li>
            </ul>
        </div>
    </div>
    <!-- /TOP HEADER -->
    <!-- MAIN HEADER -->
    <div id="header">
        <!-- container -->
        <div class="container">
            <!-- row -->
            <div class="row">
                <!-- LOGO -->
                <div class="col-md-3">
                    <div class="header-logo">
                        <a href="@Url.Action("Index","Home")" class="logo">
                            <img src=@Url.Content("/Content/img/logo.png") alt="">
                        </a>
                    </div>
                </div>
                <!-- /LOGO -->
                <!-- SEARCH BAR -->
                <div class="col-md-6">
                    <div class="header-search">
                        <form>
                            <select class="input-select">

                                <option value="0">Danh mục</option>

                                @foreach (var item in Model)
                                {
                                    <option value=@item.MaLoai>@item.TenLoai</option>
                                }

                            </select>
                            <input class="input" placeholder="Tìm kiếm">
                            <button class="search-btn">Tìm kiếm</button>
                        </form>
                    </div>
                </div>
                <!-- /SEARCH BAR -->
                <!-- ACCOUNT -->
                <div class="col-md-3 clearfix">
                    <div class="header-ctn">
                        <!-- Wishlist -->
                        <div>
                            <a href="#">
                                <i class="fa fa-heart-o"></i>
                                <span>Mục yêu thích</span>
                                <div class="qty">2</div>
                            </a>
                        </div>
                        <!-- /Wishlist -->
                        <!-- Cart -->
                        <div class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" aria-expanded="true">
                                <i class="fa fa-shopping-cart"></i>
                                <span>Giỏ hàng</span>
                                <div class="qty">3</div>
                            </a>
                            <div class="cart-dropdown">
                                <div class="cart-list">
                                    <div class="product-widget">
                                        <div class="product-img">
                                            <img src="./img/product01.png" alt="">
                                        </div>
                                        <div class="product-body">
                                            <h3 class="product-name"><a href="#">product name goes here</a></h3>
                                            <h4 class="product-price"><span class="qty">1x</span>$980.00</h4>
                                        </div>
                                        <button class="delete"><i class="fa fa-close"></i></button>
                                    </div>

                                    <div class="product-widget">
                                        <div class="product-img">
                                            <img src="./img/product02.png" alt="">
                                        </div>
                                        <div class="product-body">
                                            <h3 class="product-name"><a href="#">product name goes here</a></h3>
                                            <h4 class="product-price"><span class="qty">3x</span>$980.00</h4>
                                        </div>
                                        <button class="delete"><i class="fa fa-close"></i></button>
                                    </div>
                                </div>
                                <div class="cart-summary">
                                    <small>3 Item(s) selected</small>
                                    <h5>SUBTOTAL: $2940.00</h5>
                                </div>
                                <div class="cart-btns">
                                    <a href="#">View Cart</a>
                                    <a href="#">Checkout  <i class="fa fa-arrow-circle-right"></i></a>
                                </div>
                            </div>
                        </div>
                        <!-- /Cart -->
                        <!-- Menu Toogle -->
                        <div class="menu-toggle">
                            <a href="#">
                                <i class="fa fa-bars"></i>
                                <span>Menu</span>
                            </a>
                        </div>
                        <!-- /Menu Toogle -->
                    </div>
                </div>
                <!-- /ACCOUNT -->
            </div>
            <!-- row -->
        </div>
        <!-- container -->
    </div>
    <!-- /MAIN HEADER -->

Views/Shared/_HomePageLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <title>Nước hoa mĩ phẩm</title> 

    <!-- Google font -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,500,700" rel="stylesheet">

    <!-- Bootstrap -->
    <link type="text/css" rel="stylesheet" href=@Url.Content("/Content/css/bootstrap.min.css") />

    <!-- Slick -->
    <link type="text/css" rel="stylesheet" href=@Url.Content("/Content/css/slick.css") />
    <link type="text/css" rel="stylesheet" href=@Url.Content("/Content/css/slick-theme.css") />

    <!-- nouislider -->
    <link type="text/css" rel="stylesheet" href=@Url.Content("/Content/css/nouislider.min.css") />

    <!-- Font Awesome Icon -->
    <link rel="stylesheet" href=@Url.Content("/Content/css/font-awesome.min.css")>

    <!-- Custom stlylesheet -->
    <link type="text/css" rel="stylesheet" href=@Url.Content("/Content/css/style.css") />

</head>
<body>
    <!-- HEADER -->
    <header>
        @Html.Action("LoadHeader","RenderLayout")
    </header>
    <!-- NAVIGATION -->
    <nav id="navigation">
        @Html.Partial("_Navigation")
    </nav>
    <!-- /NAVIGATION -->
    <!-- SECTION -->
    @RenderBody();
    <!-- /SECTION -->
    <!-- NEWSLETTER -->
    <div id="newsletter" class="section">
        @Html.Partial("_NewsLetter")
    </div>
    <!-- /NEWSLETTER -->
    <!-- FOOTER -->
    <footer id="footer">
        @Html.Partial("_Footer")
    </footer>
    <!-- /FOOTER -->
    <!-- jQuery Plugins -->
    <script src="~/Scripts/jquery.min.js"></script>
    <script src="~/Scripts/js/bootstrap.min.js"></script>
    <script src="~/Scripts/js/slick.min.js"></script>
    <script src="~/Scripts/js/nouislider.min.js"></script>
    <script src="~/Scripts/js/jquery.zoom.min.js"></script>
    <script src="~/Scripts/js/main.js"></script>

</body>
</html>

Views/Shared/_MyLayout.cshtml
@{
    ViewBag.Title = "_MyLayout";
}

<h2>_MyLayout</h2>

Views/Shared/_Navigation.cshtml
<!-- container -->
<div class="container">
    <!-- responsive-nav -->
    <div id="responsive-nav">
        <!-- NAV -->
        <ul class="main-nav nav navbar-nav">
            <li class="active"><a href="#">Trang chủ</a></li>
            <li><a href="#">Bán chạy</a></li>
            <li><a href="#">Danh mục</a></li>
            <li><a href="#">Nước hoa</a></li>
            <li><a href="#">Son</a></li>
            <li><a href="#">Quần áo</a></li>
            <li><a href="#">Giày dép</a></li>
        </ul>
        <!-- /NAV -->
    </div>
    <!-- /responsive-nav -->
</div>
<!-- /container -->

Views/Shared/_NewsLetter.cshtml
<!-- container -->
<div class="container">
    <!-- row -->
    <div class="row">
        <div class="col-md-12">
            <div class="newsletter">
                <p>Đăng ký để nhận thông tin <strong>Mới</strong></p>
                <form>
                    <input class="input" type="email" placeholder="nhập địa chỉ email">
                    <button class="newsletter-btn"><i class="fa fa-envelope"></i> Theo dõi</button>
                </form>
                <ul class="newsletter-follow">
                    <li>
                        <a href="#"><i class="fa fa-facebook"></i></a>
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-twitter"></i></a>
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-instagram"></i></a>
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-pinterest"></i></a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <!-- /row -->
</div>
<!-- /container -->

Views/Shared/_ProductPageLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <title>Nước hoa mĩ phẩm</title>

    <!-- Google font -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,500,700" rel="stylesheet">

    <!-- Bootstrap -->
    <link type="text/css" rel="stylesheet" href=@Url.Content("/Content/css/bootstrap.min.css") />

    <!-- Slick -->
    <link type="text/css" rel="stylesheet" href=@Url.Content("/Content/css/slick.css") />
    <link type="text/css" rel="stylesheet" href=@Url.Content("/Content/css/slick-theme.css") />

    <!-- nouislider -->
    <link type="text/css" rel="stylesheet" href=@Url.Content("/Content/css/nouislider.min.css") />

    <!-- Font Awesome Icon -->
    <link rel="stylesheet" href=@Url.Content("/Content/css/font-awesome.min.css")>

    <!-- Custom stlylesheet -->
    <link type="text/css" rel="stylesheet" href=@Url.Content("/Content/css/style.css") />


</head>
<body>
    <!-- HEADER -->
    <header>
        @Html.Partial("_Header")
    </header>
    <!-- /HEADER -->
    <!-- NAVIGATION -->
    <nav id="navigation">
        @Html.Partial("_Navigation")
    </nav>
    <!-- /NAVIGATION -->
    @RenderBody();
    
    <!-- NEWSLETTER -->
    <div id="newsletter" class="section">
        @Html.Partial("_NewsLetter")
    </div>
    <!-- /NEWSLETTER -->
    <!-- FOOTER -->
    <footer id="footer">
        @Html.Partial("_Footer")
    </footer>
    <!-- /FOOTER -->
    <!-- jQuery Plugins -->
    <script src="~/Scripts/jquery.min.js"></script>
    <script src="~/Scripts/js/bootstrap.min.js"></script>
    <script src="~/Scripts/js/slick.min.js"></script>
    <script src="~/Scripts/js/nouislider.min.js"></script>
    <script src="~/Scripts/js/jquery.zoom.min.js"></script>
    <script src="~/Scripts/js/main.js"></script>

</body>
</html>

Views/Shared/_StorePageLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <title>Nước hoa mĩ phẩm</title>

    <!-- Google font -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,500,700" rel="stylesheet">

    <!-- Bootstrap -->
    <link type="text/css" rel="stylesheet" href=@Url.Content("/Content/css/bootstrap.min.css") />

    <!-- Slick -->
    <link type="text/css" rel="stylesheet" href=@Url.Content("/Content/css/slick.css") />
    <link type="text/css" rel="stylesheet" href=@Url.Content("/Content/css/slick-theme.css") />

    <!-- nouislider -->
    <link type="text/css" rel="stylesheet" href=@Url.Content("/Content/css/nouislider.min.css") />

    <!-- Font Awesome Icon -->
    <link rel="stylesheet" href=@Url.Content("/Content/css/font-awesome.min.css")>

    <!-- Custom stlylesheet -->
    <link type="text/css" rel="stylesheet" href=@Url.Content("/Content/css/style.css") />


</head>
<body>
    <!-- HEADER -->
    <header>
        @Html.Partial("_Header")
    </header>
    <!-- /HEADER -->
    <!-- NAVIGATION -->
    <nav id="navigation">
        @Html.Partial("_Navigation")
    </nav>
    <!-- /NAVIGATION -->
    @RenderBody();
    <!-- NEWSLETTER -->
    <div id="newsletter" class="section">
        @Html.Partial("_NewsLetter")
    </div>
    <!-- /NEWSLETTER -->
    <!-- FOOTER -->
    <footer id="footer">
        @Html.Partial("_Footer")
    </footer>
    <!-- /FOOTER -->
    <!-- jQuery Plugins -->
    <script src="~/Scripts/jquery.min.js"></script>
    <script src="~/Scripts/js/bootstrap.min.js"></script>
    <script src="~/Scripts/js/slick.min.js"></script>
    <script src="~/Scripts/js/nouislider.min.js"></script>
    <script src="~/Scripts/js/jquery.zoom.min.js"></script>
    <script src="~/Scripts/js/main.js"></script>

</body>
</html>